Name subnets after the AZ they are deployed in.
pulumi/pulumi-awsx pull request #917
Opened 2022-09-26 18:00 UTC by jkodroff

Fixes #913

Note that this change, as implemented, will cause a replace for existing resources as the name of the resource is currently tied to the `Name` tag. Happy to separate the two based on PR feedback, or we can include a release note indicating how to alias to prevent the replace.

2022-09-27 20:34 UTC, guineveresaenger commented
/run-acceptance-tests

2022-09-29 00:26 UTC, jkodroff commented
@lukehoban Do you have any thoughts on how we should communicate this change to users: Are migration (alias) instructions sufficient?

2022-10-10 09:16 UTC, danielrbradley requested changes

2022-10-10 09:16 UTC, danielrbradley commented on awsx/ec2/subnetDistributor.ts
>        });
Let's add aliases here as you suggested to maintain backward compatibility with the old names.

2023-08-28 23:06 UTC, jkodroff commented
@danielrbradley It's been dormant for a while, but I picked this back up. Unit tests look like they pass and I just need to run it against a test Pulumi program made before this change to ensure no resources get re-created.

2023-08-29 08:31 UTC, danielrbradley reviewed
This looks great with the aliases added in! Let me know once you've confirmed the upgrade path works without recreation and I'll approve.

2024-09-19 19:26 UTC, closed without merging