feat: allow tagging public subnets
pulumi/pulumi-awsx pull request #921
Opened 2022-09-28 19:59 UTC by rawkode

Security group rules are based on tagging and it's a common use-case to allow ingress and egress based on these tags, as such we should support tagging the public subnets which are most likely to require ingress.

2022-09-29 19:51 UTC, lukehoban commented on awsx/schema.json
> +                    }
This will need a description to populate documentation.

2022-09-29 19:51 UTC, lukehoban commented on CHANGELOG.md
> +* Allow tagging public subnets on VPC for security group matching
Should we add equivalents to this for all the other subsets of resources we're creating as well?  Or at least also `privateSubnetTags`?

2022-10-04 14:29 UTC, jkodroff commented
I believe that we have a bug in the existing implementation. `subnets` already has a `tags` field, but it's not actually applied to the subnets: https://github.com/pulumi/pulumi-awsx/issues/922

2022-10-04 14:40 UTC, danielrbradley requested changes
I don't think this new property should be necissary - I think we're just missing applying the tags which we've already got to the subnets.

If we need more options around specific tags on specific subnets then we'll need a more complete design which also covers all other types of subnet.

2023-08-03 13:22 UTC, closed without merging